export const MOTIVATION_QUOTES = [
  { text: "The goal of a successful trader is to make the best trades. Money is secondary.", author: "Alexander Elder" },
  { text: "In trading, it's not about how much you make, but how much you don't lose.", author: "Bernard Baruch" },
  { text: "The market is a device for transferring money from the impatient to the patient.", author: "Warren Buffett" },
  { text: "Risk comes from not knowing what you're doing.", author: "Warren Buffett" },
  { text: "The trend is your friend until the end when it bends.", author: "Ed Seykota" },
  { text: "Cut your losses and let your profits run.", author: "David Ricardo" },
  { text: "Plan your trade and trade your plan.", author: "Anonymous" },
  { text: "The most important thing is to have a system and stick to it.", author: "Jesse Livermore" },
  { text: "Markets are never wrong — opinions often are.", author: "Jesse Livermore" },
  { text: "A peak performance trader is totally committed to being the best and doing whatever it takes to be the best.", author: "Van K. Tharp" },
  { text: "The key to trading success is emotional discipline. If intelligence were the key, there would be a lot more people making money trading.", author: "Victor Sperandeo" },
  { text: "I always define my risk, and I don't have to worry about it.", author: "Tony Saliba" },
  { text: "One of the most valuable things a trader can do is keep a detailed journal.", author: "Anonymous" },
  { text: "Do not focus on making money; focus on protecting what you have.", author: "Paul Tudor Jones" },
  { text: "The elements of good trading are: cutting losses, cutting losses, and cutting losses.", author: "Ed Seykota" },
  { text: "Amateurs want to be right. Professionals want to make money.", author: "Anonymous" },
  { text: "What seems too high and risky to the majority generally goes higher, and what seems low and cheap generally goes lower.", author: "William O'Neil" },
  { text: "Know what you own, and know why you own it.", author: "Peter Lynch" },
  { text: "The stock market is filled with individuals who know the price of everything, but the value of nothing.", author: "Philip Fisher" },
  { text: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin" },
];
